// product
export const GET_VARIANT = 'GET_VARIANT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_PRODUCTS_ERROR = 'FETCH_PRODUCTS_ERROR';
export const FETCH_FILTERED_PRODUCTS = 'FETCH_FILTERED_PRODUCTS';
export const IS_FETCHING = 'IS_FETCHING';
export const SELECTED_VARIANT = 'SELECTED_VARIANT';

// cart
export const IS_OPEN = 'IS_OPEN';
export const ADD_TO_CART_VARIANT = 'ADD_TO_CART_VARIANT';
export const MERGE_VARIANTS_IN_CART = 'MERGE_VARIANTS_IN_CART';
export const REMOVE_FROM_CART_VARIANT = 'REMOVE_FROM_CART_VARIANT';
export const REMOVE_ALL_FROM_CART_VARIANT = 'REMOVE_ALL_FROM_CART_VARIANT';
